In [1]:
import numpy as np

In [17]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
a = np.arange(20,30,2)
a

array([20, 22, 24, 26, 28])

In [25]:
a[:5]

array([20, 22, 24, 26, 28])

In [31]:
a[:5:2]

array([20, 22, 24, 26, 28])

In [34]:
a2= np.arange(1,10).reshape(3,3)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a2[2,2]

9

In [41]:
a2[:,1]

array([2, 5, 8])

In [44]:
a3= np.arange(10,30).reshape(4,5)
a3

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [46]:
a3[1:,2:4]

array([[17, 18],
       [22, 23],
       [27, 28]])

In [50]:
a4= np.arange(10,30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [51]:
a4[:3] = 6

In [52]:
a4

array([ 6,  6,  6, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [55]:
a = np.random.randint(1,100,15)
a

array([91, 10, 37, 96, 69, 29, 29, 49, 55, 69, 55, 78, 18, 92, 34])

In [56]:
a > 50

array([ True, False, False,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True, False])

In [57]:
a[a>50]

array([91, 96, 69, 55, 69, 55, 78, 92])

In [63]:
a[(a > 80)|(a > 60)]

array([91, 96, 69, 69, 78, 92])

In [65]:
(a > 80)|(a > 60)

array([ True, False, False,  True,  True, False, False, False, False,
        True, False,  True, False,  True, False])